### ISSUE TITLE
订阅更新后，选择订阅，过一会儿就闪退

### ISSUE THREAD

**Issue by mogudy** [2dust/clashN#99]
在 release 下载的 clashN 和 clashN-Core ，都解压到了同一个文件夹

运行后，订阅成功解析和导入，但是选择该订阅后闪退

日志：

```
2022-08-23 00:27:26,306 [1] INFO  Log1 - clashN start up | clashN - V1.20 - 2022/08/11 | D:\tools\ClashN\clashN.exe
2022-08-23 00:27:27,226 [6] DEBUG Log2 - 
2022-08-23 00:27:27,226 [6] DEBUG Log2 - System.Exception
   at clashN.Handler.CoreHandler.CoreStart(ProfileItem item)
2022-08-23 00:27:58,448 [12] DEBUG Log2 - CurrentDomain_UnhandledException
2022-08-23 00:27:58,449 [12] DEBUG Log2 - System.Net.Http.HttpRequestException: 由于目标计算机积极拒绝，无法连接。 (127.0.0.1:9090)
 ---> System.Net.Sockets.SocketException (10061): 由于目标计算机积极拒绝，无法连接。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at clashN.Base.HttpClientHelper.PutAsync(String url, Dictionary`2 headers)
   at clashN.Handler.MainFormHandler.ClashConfigReload(String filePath)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
2022-08-23 00:29:09,289 [1] INFO  Log1 - clashN start up | clashN - V1.20 - 2022/08/11 | D:\tools\ClashN\clashN.exe
2022-08-23 00:29:10,200 [6] DEBUG Log2 - 
2022-08-23 00:29:10,200 [6] DEBUG Log2 - System.Exception
   at clashN.Handler.CoreHandler.CoreStart(ProfileItem item)

```

订阅地址之前在 v2rayN 的 issue 里面发送到邮箱了， issue 号 2575。

非常感谢

**Comment by mogudy** [comment]
本地消息窗口提示：
```
time="2022-08-23T01:07:49+08:00" level=info msg="Start initial provider tly"
time="2022-08-23T01:07:49+08:00" level=fatal msg="Parse config error: rules[0] [RULE-SET,Special,DIRECT] error: unsupported rule type RULE-SET"

Rule->Rule
Refresh proxies
Refresh proxies

```

本地文件、更新订阅（转换）、更新时间都有内容

日志文件里面多了一行
```
2022-08-23 00:41:39,387 [4] INFO  Log1 - UpdateTaskRun
2022-08-23 01:07:49,165 [22] DEBUG Log2 - 
2022-08-23 01:07:49,165 [22] DEBUG Log2 - System.Exception
   at clashN.Handler.CoreHandler.CoreStart(ProfileItem item)

```

过一会儿就闪退了

**Comment by 2dust** [comment]
`time="2022-08-23T01:07:49+08:00" level=fatal msg="Parse config error: rules[0] [RULE-SET,Special,DIRECT] error: unsupported rule type RULE-SET"`

clash core 不支持 `RULE-SET`
切换成clash.meta core 或换成clash p core

**Comment by mogudy** [comment]
谢谢，已解决
